version: "3"

# 各コンテナの情報
services:
  # postgres サービス
  postgres:
    # コンテナの名前
    container_name: postgres
    # Dockerfile のディレクトリパス
    build:
      context: .
      dockerfile: ./docker/postgresql/Dockerfile
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    # postgres 設定
    environment:
      - POSTGRES_USER=app_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=develop
      - TZ=Japan
    ports:
      - "5432:5432"
    expose:
      - "5432"
    tty: true

  # golang アプリケーション
  app:
    container_name: app
    # postgres をビルドした後に app をビルド
    depends_on:
      - postgres
    # Dockerfile を指定
    build:
      context: .
      dockerfile: ./docker/golang/Dockerfile
    # GOPATHを指定
    environment:
      - GOPATH=/go
      - TZ=Asia/Tokyo
    working_dir: /go/src/app
    # フォルダ共有（ホストOS:コンテナ）
    volumes:
      - type: bind
        source: .
        target: /go/src/app
    # docker-compose run 実行時に実行されるコマンド
    # command: go run main.go
    ports:
      - "3000:3000"
    tty: true # コンテナの永続化

volumes:
  postgres_volume:
