swagger: '2.0'
info:
  version: '1.0.0'
  title: E-Food
schemes: [http]
host: e-food.com
basePath: /v1
consumes: [application/json]
produces: [application/json]
paths:
  /register:
    post:
      description: 'To register a new user'
      tags: [user]
      operationId: Register
      consumes:
        - 'application/json'
      parameters:
        - name: 'signup'
          in: 'body'
          required: true
          description: 'Registeration Payload'
          schema:
            $ref: '#/definitions/RegisterUser'
      responses:
        200:
          description: Successful registeration
          schema:
            $ref: '#/definitions/SuccessResponse'
        400:
          description: Bad Request
        404:
          schema:
            type: string
          description: User not found
        500:
          schema:
            type: string
          description: Server error
definitions:
  RegisterUser:
    type: object
    required: [email,fname,password,phoneNo]
    properties:
      email:
        type: string
      fname:
        type: string
      lname:
        type: string
      password:
        type: string
      phoneNo:
        type: string
  SuccessResponse:
    type: object
    properties:
      success:
        type: boolean
      message:
        type: string